PDAF: comment unused loop to avoid  `unused-but-set-variable` error
```
$TSMP/models/parflow_pdaf/pfsimulator/parflow_lib/solver_richards.c:1821:12: error: variable 'dx' set but not used [-Werror,-Wunused-but-set-variable]
    double dx, dy;
           ^
```