parflow: fix compilation error, correct type of PseudoAdvanceRichards
```
eTSMP/parflow/pfsimulator/parflow_lib/solver_richards.c(4112): error #303: explicit type is missing ("int" assumed)
  PseudoAdvanceRichards(PFModule * this_module, double start_time,      /* Starting time */
  ^

eTSMP/parflow/pfsimulator/parflow_lib/solver_richards.c(4112): error #147: declaration is incompatible with "void PseudoAdvanceRichards(PFModule *, double, double, PFModule *, Vector *, Vector **, Vector **, Vector **)" (declared at line 1169 of "/p/scratch/cjibg36/jibg3683/DATAASSIMILATION/TSMP-PDAF/eTSMP/parflow/pfsimulator/parflow_lib/parflow_proto.h")
  PseudoAdvanceRichards(PFModule * this_module, double start_time,      /* Starting time */
  ^
```